services:
  # PocketBase
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8080"
    volumes:
      - ./pb_migrations:/pb/pb_migrations
    command:
      - serve
      - --http=0.0.0.0:8080
      - --automigrate
  # Mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # HTTP UI port
